//go:build integration

package integration

import (
	"context"
	"testing"

	"github.com/dexisback/YellowBird/internal/domain/job"
	"github.com/dexisback/YellowBird/internal/testutil"
	"github.com/google/uuid"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"gorm.io/gorm"
)

func TestJobRepositoryCRUD(t *testing.T) {
	ctx := context.Background()
	db := testutil.NewPostgres(t)
	repo := job.NewRepository(db)

	mediaID := uuid.New()
	j := &job.Job{
		MediaID:      mediaID,
		Type:         job.TypeTranscode,
		TargetHeight: intPtr(720),
		Status:       job.StatusQueued,
	}
	require.NoError(t, repo.Create(ctx, j))
	assert.NotEqual(t, uuid.Nil, j.ID, "ID should be generated by the database")

	got, err := repo.GetByID(ctx, j.ID)
	require.NoError(t, err)
	assert.Equal(t, j.ID, got.ID)
	assert.Equal(t, mediaID, got.MediaID)
	assert.Equal(t, job.TypeTranscode, got.Type)
	assert.Equal(t, intPtr(720), got.TargetHeight)
	assert.Equal(t, job.StatusQueued, got.Status)

	t.Run("update", func(t *testing.T) {
		got.Status = job.StatusCompleted
		got.Progress = 100
		require.NoError(t, repo.Update(ctx, got))

		updated, err := repo.GetByID(ctx, j.ID)
		require.NoError(t, err)
		assert.Equal(t, job.StatusCompleted, updated.Status)
		assert.Equal(t, 100, updated.Progress)
	})

	t.Run("get missing returns not found", func(t *testing.T) {
		_, err := repo.GetByID(ctx, uuid.New())
		assert.ErrorIs(t, err, gorm.ErrRecordNotFound)
	})

	t.Run("delete", func(t *testing.T) {
		require.NoError(t, repo.Delete(ctx, j.ID))
		_, err := repo.GetByID(ctx, j.ID)
		assert.ErrorIs(t, err, gorm.ErrRecordNotFound)
	})
}

func TestJobRepositoryListByMedia(t *testing.T) {
	ctx := context.Background()
	db := testutil.NewPostgres(t)
	repo := job.NewRepository(db)

	mediaID := uuid.New()
	otherMediaID := uuid.New()

	for i := 0; i < 3; i++ {
		j := &job.Job{MediaID: mediaID, Type: job.TypeThumbnail, Status: job.StatusQueued}
		require.NoError(t, repo.Create(ctx, j))
	}
	other := &job.Job{MediaID: otherMediaID, Type: job.TypeThumbnail, Status: job.StatusQueued}
	require.NoError(t, repo.Create(ctx, other))

	jobs, err := repo.ListByMedia(ctx, mediaID)
	require.NoError(t, err)
	assert.Len(t, jobs, 3)
	for _, j := range jobs {
		assert.Equal(t, mediaID, j.MediaID)
	}
}

func TestJobRepositoryListQueued(t *testing.T) {
	ctx := context.Background()
	db := testutil.NewPostgres(t)
	repo := job.NewRepository(db)

	mediaID := uuid.New()
	queued := &job.Job{MediaID: mediaID, Type: job.TypePreview, Status: job.StatusQueued}
	require.NoError(t, repo.Create(ctx, queued))

	running := &job.Job{MediaID: mediaID, Type: job.TypePreview, Status: job.StatusRunning}
	require.NoError(t, repo.Create(ctx, running))

	jobs, err := repo.ListQueued(ctx)
	require.NoError(t, err)
	require.Len(t, jobs, 1)
	assert.Equal(t, queued.ID, jobs[0].ID)
}
