FROM golang:1.24-alpine AS builder

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN CGO_ENABLED=0 GOOS=linux go build \
    -o /yellowbird-worker \
    ./cmd/worker

FROM alpine:3.22

WORKDIR /app

RUN apk add --no-cache ca-certificates ffmpeg

COPY --from=builder /yellowbird-worker /app/yellowbird-worker

CMD ["/app/yellowbird-worker"]

